name: base

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
# scipy
  - numpy 
  - xarray 
  - pandas 
  - cartopy 
  - matplotlib 
  - seaborn 
  - geopy 
  - basemap
  - netcdf4
  - cis
  - bokeh
  - metpy
  - jupyter
  - ipykernel
  - notebook >=5.6.0
  - scipy
  - scikit-learn
  - jupyterlab
  - nc-time-axis
  - PyTables
  - xlrd
  - intake
  - intake-esm
  - memory_profiler
  - plotly
  - ipyleaflet
  - rasterio
  - tqdm
  - requests
  - pillow
  - branca
  - geopandas
  - voila
  - nodejs
  - pythreejs
  - bqplot
  - psyplot
  - psy-maps 
  - psyplot-gui 
  - psy-reg 
  - cdsapi 
  - folium
  - basemap-data-hires
  - plotly
  - rasterstats
  - cfgrib
  - cdo
  - nco
  - jupytext
  - pydap
  - rise
  - papermill
  - geonum
  - pip
  - pyaerocom
  - pyresample
  - pip:
      - dask_labextension
      - ipydatawidgets
      - sidecar
      - geojsoncontour
      - nbgitpuller
      - pysplit